-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 14:21:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_poçosolidário
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_poçosolidário
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_poçosolidário` DEFAULT CHARACTER SET utf8 ;
USE `db_poçosolidário` ;

-- -----------------------------------------------------
-- Table `db_poçosolidário`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_poçosolidário`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `endereço` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `telefone` BIGINT NOT NULL,
  `e-mail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_poçosolidário`.`tb_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_poçosolidário`.`tb_tipo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_tipo_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_tipo_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_poçosolidário`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_poçosolidário`.`tb_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_poçosolidário`.`tb_post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(255) NOT NULL,
  `localização` VARCHAR(255) NOT NULL,
  `legenda` VARCHAR(255) NOT NULL,
  `feedback` VARCHAR(255) NULL,
  `doação` TINYINT NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_post_tb_usuario1_idx` (`tb_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_post_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_poçosolidário`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
